# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  hello-world: afiune/hello-world@dev:1

# Orchestrate or schedule a set of jobs
workflows:
  hello-world:
    # Run the welcome/run job in its own container
    jobs:
      - hello-world/vuln-scan:
          registry: "index.docker.io"
          repository: "techallylw/lacework-cli"
